// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3498IlomHHCS8k6J8WoSS3fuNb2yUOaw',
    appId: '1:971461435297:web:a0ca6e24636ec83333b5e0',
    messagingSenderId: '971461435297',
    projectId: 'nestly-db1cf',
    authDomain: 'nestly-db1cf.firebaseapp.com',
    storageBucket: 'nestly-db1cf.firebasestorage.app',
    measurementId: 'G-S9C2XJW38M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHKLwqREwKxBl2AFZYZPUF0r-zJoTNlzg',
    appId: '1:971461435297:android:9332c35c24e7bb1d33b5e0',
    messagingSenderId: '971461435297',
    projectId: 'nestly-db1cf',
    storageBucket: 'nestly-db1cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChTNNun9K8_XPS_aWFLaeV3teS7GCplJA',
    appId: '1:971461435297:ios:f2b4772286d5976933b5e0',
    messagingSenderId: '971461435297',
    projectId: 'nestly-db1cf',
    storageBucket: 'nestly-db1cf.firebasestorage.app',
    iosBundleId: 'com.example.planningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChTNNun9K8_XPS_aWFLaeV3teS7GCplJA',
    appId: '1:971461435297:ios:f2b4772286d5976933b5e0',
    messagingSenderId: '971461435297',
    projectId: 'nestly-db1cf',
    storageBucket: 'nestly-db1cf.firebasestorage.app',
    iosBundleId: 'com.example.planningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3498IlomHHCS8k6J8WoSS3fuNb2yUOaw',
    appId: '1:971461435297:web:37148aebb6bfbc7f33b5e0',
    messagingSenderId: '971461435297',
    projectId: 'nestly-db1cf',
    authDomain: 'nestly-db1cf.firebaseapp.com',
    storageBucket: 'nestly-db1cf.firebasestorage.app',
    measurementId: 'G-9TTS37BF47',
  );
}
